#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src/"])
env["SHLIBPREFIX"] = ""

sources = Glob("src/*.cpp")
library = env.SharedLibrary(
    "bin/non_zero_path_tessellator{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
